# Generated by Django 5.2.13 on 2026-04-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_app", "0002_notification_targets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("friend_request", "Friend Request"),
                    ("friend_accept", "Friend Accept"),
                    ("post_new", "Post New"),
                    ("post_like", "Post Like"),
                    ("post_comment", "Post Comment"),
                    ("group", "Group"),
                    ("system", "System"),
                ],
                default="system",
                max_length=30,
            ),
        ),
    ]
