# Generated by Django 5.2.13 on 2026-04-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="avatar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
