# Generated by Django 5.2.13 on 2026-04-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("slide", "Slide"),
                    ("report", "Report"),
                    ("exam", "Exam"),
                    ("note", "Note"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
    ]
